CREATE TABLE IF NOT EXISTS profit_loss_report (
    date DATE PRIMARY KEY,
    stocks_realised DECIMAL(15,2) DEFAULT 0,
    stocks_unrealised DECIMAL(15,2) DEFAULT 0,
    fo_realised DECIMAL(15,2) DEFAULT 0,
    fo_unrealised DECIMAL(15,2) DEFAULT 0,
    stock_pl DECIMAL(15,2) DEFAULT 0,
    fo_pl DECIMAL(15,2) DEFAULT 0,
    total_pl DECIMAL(15,2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 